# Generated by Django 5.1.3 on 2024-11-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='operational_activity',
        ),
        migrations.AddField(
            model_name='report',
            name='operational_activity',
            field=models.ManyToManyField(to='construction_management.operationalactivity'),
        ),
    ]
