# Generated by Django 5.1.3 on 2024-11-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0002_operationalactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationalactivity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operationalactivity',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
