# Generated by Django 5.1.3 on 2024-11-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0003_construction_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalactivity',
            options={'verbose_name': 'Operational Activity', 'verbose_name_plural': 'Operational Activities'},
        ),
    ]
