# Generated by Django 5.1.3 on 2024-11-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0004_alter_operationalactivity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='operational_activity',
        ),
        migrations.AddField(
            model_name='report',
            name='operational_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='construction_management.operationalactivity'),
        ),
    ]
