# Generated by Django 5.1.3 on 2024-11-22 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0005_remove_report_operational_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='images',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='attachments/', verbose_name='Attachment')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction_management.report', verbose_name='Report')),
            ],
        ),
    ]
