# Generated by Django 5.1.3 on 2024-11-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_management', '0007_report_images_delete_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='working_hours',
            field=models.CharField(default='08:00-17:00', max_length=50),
        ),
    ]
